CareerWeb/Areas/Admin/Controllers/EmployeeController.cs
using Model.Dao;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace CareerWeb.Areas.Admin.Controllers
{
    public class EmployeeController : Controller
    {
        // GET: Admin/Employee
        public ActionResult Index()
        {
            var model = new EmployeeDao().ListEmployees();
            return View(model);
        }
        public ActionResult DeleteEmployee(Guid id)
        {
            new EmployeeDao().Delete(id);
            return RedirectToAction("Index");
        }
        public ActionResult DetailEmployee(Guid id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var employee = new EmployeeDao().FindById(id);
            return View(employee);
        }
    }
}

CareerWeb/Controllers/ArticleController.cs
using CareerWeb.Models;
using iTextSharp.text.pdf.qrcode;
using Model.Dao;
using Model.EF;
using System;
using System.Collections.Generic;
using System.Data.Entity.Infrastructure;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;

namespace CareerWeb.Controllers
{
    public class ArticleController : Controller
    {
        // GET: Article
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public JsonResult ListCategorySmallArticle(int parentID)
        {
            var listCategory = new CategoryArticleDao().ListByParentID(parentID);
            if(listCategory == null)
            {
                return Json(new
                {
                    status = false
                });
            }
            return Json(new
            {
                list = listCategory,
                status = true
            });
        }
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult AddAndEditArticle(FormArticle model)
        {
            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Index", "Account");
            }
            var accID = int.Parse(User.Identity.Name);
            var acc = new AccountDao().FindAccountById(accID);
            var emp = new EmployeeDao().FindById(acc.UserId);
            var article = new Article();
            if(model.typeAction == "edit")
            {
                article.ID = model.saveID;
                article.ModifyDate = DateTime.Now;
            }
            else
            {
                article.Status = "Request";
                article.CreateDate = DateTime.Now;
                article.CreateID = emp.EmployeeID;
                article.Views = 0;
            }
            article.Description = model.Description;
            article.ContentArticle = model.ContentArticle;
            article.CategoryID = model.CategorySmall;
            article.CategoryParent = model.CategoryBig;
            article.Title = model.Title;
            var file = model.Image;
            if (file != null)
            {
                var fileName = Path.GetFileName(file.FileName);
                file.SaveAs(Server.MapPath("/Assets/Client/Img/Article/" + fileName));
                var srcImage = "/Assets/Client/Img/Article/" + fileName;
                article.Image = srcImage;
            }
            if(model.typeAction == "add")
            {
                var check = new ArticleDao().Insert(article);
                var checkSecond = new CategoryArticleDao().IncreaseAmount(article.CategoryID);
                var checkThird = new CategoryArticleDao().IncreaseAmount(article.CategoryParent.Value);
            }
            else
            {
                var check = new ArticleDao().Edit(article);
            }
            return RedirectToAction("ListArticleEmployee", "Employee");
        }
        [HttpPost]
        public JsonResult ReturnArticle(int articleID)
        {
            var article = new ArticleDao().FindByID(articleID);
            if(article == null)
            {
                return Json(new
                {
                    status = false
                });
            }
            var listCate = new CategoryArticleDao().ListByParentID(article.CategoryParent.Value);
            return Json(new
            {
                status = true,
                list = listCate,
                article = article
            });
        }
        [HttpPost]
        public JsonResult DeleteArticle(int articleID)
        {
            var check = new ArticleDao().Delete(articleID);
            return Json(new
            {
                status = check
            });
        }
        public ActionResult ArticleDetail(int articleID, int lout = 1)
        {
            ViewBag.LayoutID = lout;
            var listCateBig = new CategoryArticleDao().ListParent();
            var listCate = new List<List<CategoryArticle>>();
            foreach (var item in listCateBig)
            {
                var eachList = new CategoryArticleDao().ListByParentID(item.CategoryID);
                listCate.Add(eachList);
            }
            ViewBag.ListCateBig = listCateBig;
            ViewBag.ListCate = listCate;
            var model = new ArticleDao().FindByID(articleID);
            var check = new ArticleDao().IncreaseView(articleID);
            return View(model);
        }
    }
}

CareerWeb/Controllers/OfferJobController.cs
using CareerWeb.Models;
using iTextSharp.text.pdf.qrcode;
using Model.Dao;
using Model.EF;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Threading;
using System.Web;
using System.Web.Mvc;

namespace CareerWeb.Controllers
{
    public class OfferJobController : Controller
    {
        // GET: OfferJob
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public JsonResult DeleteOffer(Guid offerID)
        {
            var check = new OfferJobDao().DeleteOffer(offerID);
            if (!check)
            {
                return Json(new
                {
                    status = false
                });
            }
            var offerJobSkill = new OfferJobSkillDao();
            var listOfferSkill = offerJobSkill.ListByOffer(offerID);
            foreach(var item in listOfferSkill)
            {
                var checkSecond = offerJobSkill.DeleteSkill(offerID, item.ChildMajor);
                if (!checkSecond)
                {
                    return Json(new
                    {
                        status = false
                    });
                }
            }
            return Json(new
            {
                status = true
            });
        }
        [HttpPost]
        public JsonResult DeleteSkillOffer(Guid offerID, int skillID)
        {
            var check = new OfferJobSkillDao().DeleteSkill(offerID, skillID);
            return Json(new
            {
                status = check
            });
        }
        [HttpPost]
        public ActionResult ReturnOffer(Guid offerID)
        {
            var jbDao = new JobMajorDao();
            var offer = new OfferJobDao().FindByID(offerID);
            var listSkill = new OfferJobSkillDao().ListByOffer(offerID);
            var listNameSkill = new List<string>();
            foreach(var item in listSkill)
            {
                listNameSkill.Add(jbDao.NameJob(item.ChildMajor));
            }
            if(offer == null)
            {
                return Json(new
                {
                    status = false
                });
            }
            return Json(new
            {
                offer = offer,
                limitDate = offer.OfferLimitDate.ToString("dd/MM/yyyy"),
                listSkill = listSkill,
                listNameSkill = listNameSkill,
                majorName = jbDao.NameJob(offer.OfferMajor),
                status = true
            });
        }
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult AddOfferOfEmployee(FormOffer model)
        {
            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Index", "Account");
            }
            var accID = int.Parse(User.Identity.Name);
            var acc = new AccountDao().FindAccountById(accID);
            var emp = new EmployeeDao().FindById(acc.UserId);
            var offerJob = new OfferJob();
            if (model.typeAction == "add")
            {
                offerJob.OfferID = Guid.NewGuid();
                offerJob.OfferCreateDate = DateTime.Now;
                offerJob.Views = 0;
                offerJob.Applications = 0;
            }
            else
            {
                offerJob.OfferID = model.saveID;
            }
            offerJob.EmployeeID = acc.UserId;
            offerJob.EnterpriseID = emp.EnterpriseID;
            offerJob.OfferName = model.offerName;
            if (model.offerDescription != null && model.offerDescription != "")
            {
                offerJob.OfferDescription = model.offerDescription;
            }
            offerJob.OfferMajor = model.offerMajor;
            offerJob.OfferPosition = model.offerPosition;
            offerJob.OfferSalary = model.offerSalary;
            offerJob.Area = model.offerArea;
            offerJob.Amount = model.offerAmount;
            offerJob.ExperienceRequest = model.offerExperience;
            offerJob.ContactEmail = model.offerEmail;
            offerJob.LearningLevelRequest = model.offerLearning;
            offerJob.OfferLimitDate = DateTime.ParseExact(model.offerLimitDate, "dd/MM/yyyy", CultureInfo.InvariantCulture);
            if(model.offerGender != "none")
            {
                offerJob.Sex = model.offerGender;
            }
            offerJob.JobAddress = model.offerAddress;
            var file = model.offerImage;
            if (file != null)
            {
                var fileName = Path.GetFileName(file.FileName);
                file.SaveAs(Server.MapPath("/Assets/Client/Img/Offer/" + fileName));
                var srcImage = "/Assets/Client/Img/Offer/" + fileName;
                offerJob.OfferImage = srcImage;
            }
            if (model.typeAction == "add")
            {
                var check = new OfferJobDao().Insert(offerJob);
            }
            else
            {
                var check = new OfferJobDao().Edit(offerJob);
            }
            if (model.offerListSkillId != null && model.offerListSkillId.Count > 0)
            {
                for (var i = 0; i < model.offerListSkillId.Count; i++)
                {
                    var offerSkill = new OfferJobSkill();
                    offerSkill.OfferID = offerJob.OfferID;
                    offerSkill.ParentMajor = model.offerListSkillParent[i];
                    offerSkill.ChildMajor = model.offerListSkillId[i];
                    var checkFalse = new OfferJobSkillDao().Insert(offerSkill);
                    if (!checkFalse) break;
                }
            }
            return RedirectToAction("ListAndCreateOffer", "Employee");
        }
    }
}

CareerWeb/Views/Employee/EmployeeList.cshtml
@model List<Model.EF.Employee>


@{
    ViewBag.Title = "EmployeeList";
    Layout = "~/Views/Shared/LayoutForEnterprise.cshtml";
}

@section cssInsert{

    <link href="http://localhost:58154/Assets/Client/Css/Employee/EmployeeList.css" rel="stylesheet" />
}

<div id="wrap">
    <div id="row">
        <a id="viec-lam" class="rower" href="#">Việc làm</a>/<a id="nha-tuyen-dung" class="rower" href="#">Nhà tuyển dụng : Quản lý</a>
        /<span id="danh-sach" class="rower">Danh sách thành viên công ty</span>
    </div>

    <div id="main">
        <div id="title">
            <h1> Danh sách thành viên công ty </h1>
        </div>

        <div id="tab-content">
            <div id="utility" class="utility">
                <div id="display-utility" class="display-utility">
                    <label>
                        Hiển thị
                        <select id="display" name="hien-thi">
                            <option value="1">1</option>
                            <option value="2">2</option>
                            <option value="5">5</option>
                            <option value="10">10</option>
                        </select>
                    </label>
                </div>

                <div id="search-utility" class="search-utility">
                    <label>
                        Tìm kiếm
                        <input type="text" name="tim-kiem" id="search" />
                    </label>
                </div>
            </div>

            <div id="tab" class="tab">
                <div id="list-employee">
                    <table>
                        <thead>
                            <tr>
                                <th>Thành viên</th>
                                <th>Chức vụ</th>
                                <th>Email</th>
                                <th>Số điện thoại</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr class="employee-rows">
                                    <td class="employee-name">
                                        @item.EmployeeName
                                    </td>

                                    <td class="position">
                                        @(new Model.Dao.PositionEmployeeDao().NamePosition(item.Position))
                                    </td>

                                    <td class="email">
                                        @item.Email
                                    </td>

                                    <td class="phone">
                                        @item.Mobile
                                    </td>

                                    <td class="action">
                                        <div class="detail-button" employee="@item.EmployeeID" onclick="deleteEmployee()">
                                            Xóa
                                        </div>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="page">
                <div class="prev"><i class="fa fa-chevron-left"></i></div>
                <div class="next"><i class="fa fa-chevron-right"></i></div>
            </div>
        </div>
    </div>
</div>

@section jsInsert{



    <script src="http://localhost:58154/Assets/Client/Js/Employee/EmployeeList.js"></script>
}

CareerWeb/Views/Employee/ListAndCreateOffer.cshtml
@model List<Model.EF.OfferJob>
@using Model.Dao
@{
    ViewBag.Title = "Offer List";
    Layout = "~/Views/Shared/LayoutForEnterprise.cshtml";
    var JobMajorDao = new JobMajorDao();
    var PositionEmployeeDao = new PositionEmployeeDao();
    var SalaryDao = new SalaryDao();
    var AreaDao = new AreaDao();
}
@section cssInsert{
    <link href="~/Assets/Client/Css/Employee/OfferList.css" rel="stylesheet" />
   
}
<main style="float: left; width: 100%; padding-bottom: 20px;">
    <div id="container-title">
        <div id="button-new"><i class="fa fa-plus"></i> THÊM MỚI</div>
        <span>Tạo đơn tuyển dụng mới</span>
    </div>
    <div id="container-offer">
    @if (Model != null && Model.Count != 0)
    {
        foreach (var item in Model)
        {
            var linkImage = item.OfferImage != null ? item.OfferImage : "/Assets/Client/Img/Common/hiring-agencies.jpg";
            <div class="each-offer">
                <div class="contain-left">
                    <img src="@linkImage" alt="" />
                </div>
                <div class="contain-mid">
                    <div class="name-offer">@item.OfferName</div>
                    <div class="offer-major">
                        <span>Lĩnh vực: </span> @(JobMajorDao.NameJob(item.OfferMajor))
                    </div>
                    <div class="position-offer">
                        <span>Vị trí tuyển dụng: </span> @(PositionEmployeeDao.NamePosition(item.OfferPosition))
                    </div>
                    <div class="email-offer">
                        <span>Email liên hệ: </span> @item.ContactEmail
                    </div>
                    <div class="contain-some-infor">
                        <div class="offer-salary">Mức lương: @(SalaryDao.NameSalary(item.OfferSalary))</div>
                        <div class="offer-area">Khu vực: @(AreaDao.FindNameArea(item.Area))</div>
                        <div class="offer-amount">Số lượng tuyển dụng: @item.Amount</div>
                    </div>
                    <div class="offer-time">
                        <span>Thời gian tuyển dụng: </span> @(item.OfferCreateDate.ToString("dd/MM/yyyy") + " - " + item.OfferLimitDate.ToString("dd/MM/yyyy"));
                    </div>
                </div>
                <div class="contain-right">
                    <div class="up-right">
                        <div class="offer-view">
                           <div> @item.Views</div>
                           Lượt xem
                        </div>
                        <div class="offer-apply">
                           <div> @item.Applications</div>
                           Ứng tuyển
                        </div>
                    </div>
                    <div class="down-right">
                        <div class="edit-offer" data-id="@item.OfferID">EDIT</div>
                        <div class="delete-offer" data-id="@item.OfferID">DELETE</div>
                    </div>
                </div>
            </div>
        }
    }
    else
    {
        <div>Bạn chưa tạo một đơn tuyển dụng nào</div>
    }
    </div>
    <div id="cover-screen">
        <div id="box-create">
            <div id="box-header">
                TẠO ĐƠN TUYỂN DỤNG
            </div>
            <div id="box-main">
                @using (Html.BeginForm("AddOfferOfEmployee", "OfferJob", FormMethod.Post, new { enctype = "multipart/form-data" }))
                {
                    <div class="each-part">
                        <label for="input-name-offer">Tên công việc: <span>*</span></label>
                        <input type="text" value="" id="input-name-offer" name="offerName" />
                    </div>
                    <div class="each-part">
                        <label for="input-major-offer">Lĩnh vực: <span>*</span> </label>
                        <input type="hidden" value="" name="offerMajor" />
                        <input type="text" value="" id="input-major-offer" data-id="" class="search-list" list="list-major-offer" />
                        <datalist id="list-major-offer">
                            @foreach (var item in ViewBag.ListMajor)
                            {
                                <option value="@item.JobName" data-id="@item.JobID" />
                            }
                        </datalist>
                    </div>
                    <div class="each-part">
                        <label for="input-position-offer">Vị trí tuyển dụng: <span>*</span> </label>
                        <select id="input-position-offer" name="offerPosition">
                            @foreach (var item in ViewBag.ListPosition)
                            {
                                <option value="@item.ID">@item.NamePosition</option>
                            }
                        </select>
                    </div>
                    <div class="each-part">
                        <label for="input-salary-offer">Mức lương: <span>*</span> </label>
                        <select id="input-salary-offer" name="offerSalary">
                            @foreach (var item in ViewBag.ListSalary)
                            {
                                <option value="@item.ID">@item.Amount</option>
                            }
                        </select>
                    </div>
                    <div class="each-part">
                        <label for="input-area-offer">Khu vực: <span>*</span> </label>
                        <select id="input-area-offer" name="offerArea">
                            @foreach (var item in ViewBag.ListArea)
                            {
                                <option value="@item.AreaId">@item.NameArea</option>
                            }
                        </select>
                    </div>
                    <div class="each-part">
                        <label for="input-email-offer">Email liên hệ: <span>*</span> </label>
                        <input type="text" value="" id="input-email-offer" name="offerEmail" />
                    </div>
                    <div class="each-part">
                        <label for="input-experience-offer">Kinh nghiệm: <span>*</span> </label>
                        <select id="input-experience-offer" name="offerExperience">
                            @foreach (var item in ViewBag.ListExperience)
                            {
                                <option value="@item.ID">@item.Time</option>
                            }
                        </select>
                    </div>
                    <div class="each-part">
                        <label for="input-learning-offer">Yêu cầu học vấn: <span>*</span> </label>
                        <select id="input-leanring-offer" name="offerLearning">
                            @foreach (var item in ViewBag.ListLearning)
                            {
                                <option value="@item.ID">@item.NameLevel</option>
                            }
                        </select>
                    </div>
                    <div class="each-part">
                        <label for="input-amount-offer">Số lượng: <span>*</span> </label>
                        <input type="tel" id="input-amount-offer" value="" name="offerAmount" />
                    </div>
                    <div class="each-part">
                        <label for="input-gender">Giới tính:  </label>
                        <select name="offerGender" id="input-gender">
                            <option value="none">Không yêu cầu</option>
                            <option value="male">Nam</option>
                            <option value="female">Nữ</option>
                        </select>
                    </div>
                    <div class="each-part">
                        <label for="input-address">Địa chỉ:  </label>
                        <input type="text" id="input-address" name="offerAddress" />
                    </div>
                    <div class="each-part">
                        <label for="input-limit-date">Hạn nộp đơn: <span>*</span> </label>
                        <input type="text" id="input-limit-date" value="" placeholder="Định dạng dd/MM/yyyy" name="offerLimitDate" />
                    </div>
                    <div class="each-part-big">
                        <div class="part-left">
                            <label style="font-weight: bold;">Ảnh giới thiệu: </label>
                        </div>
                        <div class="part-right">
                            <div id="display-image">
                                <img src="" alt="" />
                            </div>
                            <input type="file" id="imgBrowser" name="offerImage" style="display: none;" />
                            <div id="img-upload" style="border-radius: 3px;">UPLOAD</div>
                        </div>
                    </div>
                    <div class="each-part-big">
                        <div class="part-left">
                            <label style="font-weight: bold;">Kỹ năng yêu cầu: <span>*</span> </label><br />
                            <input type="text" value="" data-id="" class="search-list" id="input-skill-offer" list="list-skill-offer" placeholder="Nhập tìm kiếm" />
                            <datalist id="list-skill-offer">
                                @foreach (var item in ViewBag.ListSkill)
                                {
                                    <option value="@item.JobName" data-id="@item.JobID" data-parent="@item.JobIDParent" />
                                }
                            </datalist>
                        </div>
                        <div class="part-right">
                            <div id="container-skill">

                            </div>
                        </div>
                    </div>
                    <div class="each-part-big">
                        <div class="part-left">
                            <label style="font-weight: bold;">Mô tả chi tiết công việc: <span>*</span></label>
                        </div>
                        <div class="part-right">
                            <textarea class="ckeditor" name="offerDescription" id="offer-description"></textarea>
                        </div>
                    </div>
                    <input type="hidden" value="00000000-0000-0000-0000-000000000000" name="saveID" />
                    <input type="hidden" value="add" name="typeAction" />
                }
            </div>
            <div id="box-footer">      
                <div class="button-offer" id="cancel">CANCEL</div>
                <div class="button-offer" id="both-input" data-id="">EDIT</div>
            </div>
        </div>
    </div>
                
            

</main>
@section jsInsert{

    <script src="~/Assets/Client/Js/Employee/OfferList.js"></script>
}

CareerWeb/Views/Employee/ListArticleEmployee.cshtml
@model List<Model.EF.Article>
@using Model.Dao
@{
    ViewBag.Title = "ListArticleEmployee";
    Layout = "~/Views/Shared/LayoutForEnterprise.cshtml";
    var cateArtDao = new CategoryArticleDao();
}
@section cssInsert{
    <link href="~/Assets/Client/Css/Employee/ListArticleEmployee.css" rel="stylesheet" />
}
<main>
    <div id="box-contain">
        <div id="title-site">QUẢN LÝ BÀI VIẾT</div>
        <div id="introduce-step">
            <div id="contain-text">Các bước để tạo một bài viết và đăng lên web</div>
            <div class="text-arrow">
                <div style="margin-left: 10px; font-style: italic;">Bước 1</div>
                <img src="~/Assets/Client/Img/Common/arrow-qtstep.png" class="arrow-step" />
            </div>
            <div class="each-step">
                <img src="~/Assets/Client/Img/Common/stepArticle1.png" class="step-img" />
                <div class="step-text">
                    Nhân viên doanh nghiệp truy cập trang và đăng bài viết
                </div>
            </div>
            <div class="text-arrow">
                <div style="margin-left: 10px; font-style: italic;">Bước 2</div>
                <img src="~/Assets/Client/Img/Common/arrow-qtstep.png" class="arrow-step" />
            </div>
            <div class="each-step">
                <img src="~/Assets/Client/Img/Common/stepArticle2.png" class="step-img" />
                <div class="step-text">
                    Admin kiểm tra Bài viết hợp lệ sẽ được kích hoạt
                </div>
            </div>
        </div>
        <div id="contain-button">
            <div id="title-list"><i class="fa fa-suitcase" style="margin-right: 8px;"></i>Danh sách bài viết</div>
            <div id="button-new"><i class="fa fa-plus-square-o" style="margin-right: 8px;"></i>Thêm bài viết</div>
        </div>
        <div id="contain-list">
            @if (Model != null && Model.Count != 0)
            {
                foreach(var item in Model)
                {
                    <div class="each-article">
                        <div class="contain-left">
                            <img src="@item.Image"/>
                        </div>
                        <div class="contain-mid">
                            <div class ="title-article">@item.Title</div>
                            <div class="category">Thể loại: @cateArtDao.NameCategoryArticle(item.CategoryParent.Value)/@cateArtDao.NameCategoryArticle(item.CategoryID)</div>
                            <div class="date">
                                <span class="create">Ngày tạo: @item.CreateDate.Value.ToString("dd/MM/yyy")</span>
                                <span class="modify">Chỉnh sửa gần nhất: @(item.ModifyDate != null ? item.ModifyDate.Value.ToString("dd/MM/yyyy") : "")</span>
                            </div>
                            <div class="status">
                                Trạng thái: @item.Status
                            </div>
                            <div class="view">
                                Tổng số lượt xem: @item.Views
                            </div>
                        </div>
                        <div class="contain-right">
                            <div class="edit" data-id="@item.ID" status ="@item.Status">EDIT</div>
                            <div class="delete" data-id="@item.ID">DELETE</div>
                        </div>
                    </div>
                }
            }
            else
            {
                <div>Bạn chưa tạo bài viết nào</div>
            }
        </div>
    </div>
    <div id="box-create">
        @using (Html.BeginForm("AddAndEditArticle", "Article", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            <div class="each-part">
                <label for="input-title">Tiêu đề <span>*</span></label>
                <input id="input-title" name="Title" value="" type="text" />
            </div>
            <div class="each-part-small">
                <label for="input-category-big">Thể loại lớn<span>*</span></label>
                <select id="input-category-big" name="CategoryBig">
                    <option value="none">-- Chọn thể loại --</option>
                    @foreach(var item in ViewBag.ListCategory)
                    {
                        <option value="@item.CategoryID">@item.NameCategory</option>
                    }
                </select>
            </div>
            <div class="each-part-small">
                <label for="input-category-small">Thể loại nhỏ<span>*</span></label>
                <select id="input-category-small" name="CategorySmall">
                </select>
            </div>
            <div class="each-part">
                <label for="input-description">Mô tả <span>*</span></label>
                <textarea id="input-description" name="Description"></textarea>
            </div>
            <div class="each-part">
                <label>Hình ảnh<span>*</span></label>
                <img src="" alt="" />
                <input type="file" name="Image" />
            </div>
            <div class="each-part">
                <label for="input-content">Nội dung <span>*</span></label><br /><br />
                <textarea id="input-content" name="ContentArticle" class="ckeditor"></textarea>
            </div>
            <div id="box-footer">
                <input type="hidden" value="add" name="typeAction"/>
                <input type="hidden" value="-1" name="saveID"/>
                <div id="both-input">Thêm</div>
                <div id="cancel">Hủy</div>
            </div>
        }
    </div>
</main>
@section jsInsert{
    <script src="~/Assets/Client/Js/Employee/ListArticleEmployee.js"></script>
    }